// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opykenltutgqticfesvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9weWtlbmx0dXRncXRpY2Zlc3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTc4NzIsImV4cCI6MjA2OTMzMzg3Mn0.LYVoRjhrEd9BfkwxuKpCSIhNnMvNwvF9EuCzoPVjuHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});